# Extendable version manager with support for Ruby, Node.js, Erlang & more"
# https://asdf-vm.com/
brew "asdf"

brew "autojump"
brew "coreutils"
brew "curl"
brew "diff-so-fancy"
brew "fish"
brew "fswatch"
brew "golang"
brew "jq"


# Utility to optimize JPEG files
# https://github.com/tjko/jpegoptim
brew "jpegoptim"

# PNG file optimizer
# https://optipng.sourceforge.net/
brew "optipng"

brew "readline"
brew "rsync"
brew "rustup"
brew "sqlite"
brew "ssh-copy-id"
brew "stow"
brew "tmux"
brew "wget"
